// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImport(arg1) {
  return window['go']['main']['App']['CancelImport'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function GetImportResult(arg1) {
  return window['go']['main']['App']['GetImportResult'](arg1);
}

export function GetParentSummary() {
  return window['go']['main']['App']['GetParentSummary']();
}

export function GetPracticeFilters() {
  return window['go']['main']['App']['GetPracticeFilters']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetRecoveryState() {
  return window['go']['main']['App']['GetRecoveryState']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function PauseSession(arg1) {
  return window['go']['main']['App']['PauseSession'](arg1);
}

export function PlayMove(arg1, arg2) {
  return window['go']['main']['App']['PlayMove'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function ResumeSession() {
  return window['go']['main']['App']['ResumeSession']();
}

export function RevealSolution(arg1) {
  return window['go']['main']['App']['RevealSolution'](arg1);
}

export function StartFreePractice(arg1) {
  return window['go']['main']['App']['StartFreePractice'](arg1);
}

export function StartGuided() {
  return window['go']['main']['App']['StartGuided']();
}

export function StartLichessImport(arg1) {
  return window['go']['main']['App']['StartLichessImport'](arg1);
}

export function StartPuzzleImport(arg1) {
  return window['go']['main']['App']['StartPuzzleImport'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UseHint(arg1) {
  return window['go']['main']['App']['UseHint'](arg1);
}
