// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {importjob} from '../models';
import {domain} from '../models';

export function CancelImport(arg1:string):Promise<void>;

export function GetImportResult(arg1:string):Promise<importjob.Result>;

export function PauseSession(arg1:string):Promise<void>;

export function PlayMove(arg1:string,arg2:string):Promise<domain.MoveResult>;

export function ResumeSession():Promise<domain.SessionView>;

export function RevealSolution(arg1:string):Promise<domain.MoveResult>;

export function StartGuided():Promise<domain.SessionView>;

export function StartLichessImport(arg1:string):Promise<string>;

export function UseHint(arg1:string):Promise<domain.HintResult>;
