// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImport(arg1) {
  return window['go']['main']['App']['CancelImport'](arg1);
}

export function GetImportResult(arg1) {
  return window['go']['main']['App']['GetImportResult'](arg1);
}

export function StartLichessImport(arg1) {
  return window['go']['main']['App']['StartLichessImport'](arg1);
}
