// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {importjob} from '../models';

export function CancelImport(arg1:string):Promise<void>;

export function GetImportResult(arg1:string):Promise<importjob.Result>;

export function StartLichessImport(arg1:string):Promise<string>;
