// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {buildinfo} from '../models';

export function GetApplicationMode():Promise<string>;

export function GetBuildInfo():Promise<buildinfo.Info>;
