// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {openings} from '../models';
import {importjob} from '../models';
import {profile} from '../models';
import {training} from '../models';
import {importing} from '../models';
import {domain} from '../models';

export function AdvanceOpeningActivity(arg1:string):Promise<openings.OpeningActivityResult>;

export function AdvanceOpeningStep(arg1:string):Promise<openings.OpeningActivityResult>;

export function CancelImport(arg1:string):Promise<void>;

export function ChooseOpeningCourseFile():Promise<string>;

export function ChoosePuzzleImportFile():Promise<string>;

export function CreateBackup(arg1:boolean):Promise<string>;

export function GetImportResult(arg1:string):Promise<importjob.Result>;

export function GetOpeningHome():Promise<openings.OpeningHomeView>;

export function GetOpeningPosition(arg1:string,arg2:string,arg3:openings.Depth):Promise<openings.ExplorerPositionView>;

export function GetParentSummary():Promise<profile.Summary>;

export function GetPracticeFilters():Promise<profile.PracticeFilters>;

export function GetProfile():Promise<training.Profile>;

export function InspectOpeningCourseImport(arg1:string):Promise<importing.Inspection>;

export function InspectPuzzleImport(arg1:string):Promise<importing.Inspection>;

export function OpenDataFolder():Promise<void>;

export function PauseOpeningSession(arg1:string):Promise<void>;

export function PauseSession(arg1:string):Promise<void>;

export function PlayMove(arg1:string,arg2:string):Promise<domain.MoveResult>;

export function PlayOpeningMove(arg1:string,arg2:string):Promise<openings.OpeningActivityResult>;

export function Quit():Promise<void>;

export function RestartOpeningSession(arg1:string):Promise<openings.OpeningSessionView>;

export function RestoreBackup(arg1:string):Promise<void>;

export function ResumeOpeningSession():Promise<openings.OpeningSessionView>;

export function ResumeSession():Promise<domain.SessionView>;

export function RevealOpeningMove(arg1:string):Promise<openings.OpeningActivityResult>;

export function RevealSolution(arg1:string):Promise<domain.MoveResult>;

export function SetOpeningDepth(arg1:string,arg2:openings.Depth):Promise<void>;

export function StartFreePractice(arg1:training.PracticeRequest):Promise<domain.SessionView>;

export function StartGuided():Promise<domain.SessionView>;

export function StartOpeningCourseImport(arg1:importing.Inspection):Promise<string>;

export function StartOpeningLesson(arg1:string,arg2:string):Promise<openings.OpeningSessionView>;

export function StartOpeningReview(arg1:string):Promise<openings.OpeningSessionView>;

export function StartPuzzleImport(arg1:importing.Inspection):Promise<string>;

export function UpdateProfile(arg1:training.Profile):Promise<void>;

export function UseHint(arg1:string):Promise<domain.HintResult>;

export function UseOpeningHint(arg1:string):Promise<openings.OpeningHintResult>;
