// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {importjob} from '../models';
import {profile} from '../models';
import {training} from '../models';
import {importing} from '../models';
import {domain} from '../models';

export function CancelImport(arg1:string):Promise<void>;

export function ChooseOpeningCourseFile():Promise<string>;

export function ChoosePuzzleImportFile():Promise<string>;

export function CreateBackup(arg1:boolean):Promise<string>;

export function GetImportResult(arg1:string):Promise<importjob.Result>;

export function GetParentSummary():Promise<profile.Summary>;

export function GetPracticeFilters():Promise<profile.PracticeFilters>;

export function GetProfile():Promise<training.Profile>;

export function InspectOpeningCourseImport(arg1:string):Promise<importing.Inspection>;

export function InspectPuzzleImport(arg1:string):Promise<importing.Inspection>;

export function OpenDataFolder():Promise<void>;

export function PauseSession(arg1:string):Promise<void>;

export function PlayMove(arg1:string,arg2:string):Promise<domain.MoveResult>;

export function Quit():Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function ResumeSession():Promise<domain.SessionView>;

export function RevealSolution(arg1:string):Promise<domain.MoveResult>;

export function StartFreePractice(arg1:training.PracticeRequest):Promise<domain.SessionView>;

export function StartGuided():Promise<domain.SessionView>;

export function StartOpeningCourseImport(arg1:importing.Inspection):Promise<string>;

export function StartPuzzleImport(arg1:importing.Inspection):Promise<string>;

export function UpdateProfile(arg1:training.Profile):Promise<void>;

export function UseHint(arg1:string):Promise<domain.HintResult>;
