// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceOpeningActivity(arg1) {
  return window['go']['main']['NormalController']['AdvanceOpeningActivity'](arg1);
}

export function AdvanceOpeningStep(arg1) {
  return window['go']['main']['NormalController']['AdvanceOpeningStep'](arg1);
}

export function CancelImport(arg1) {
  return window['go']['main']['NormalController']['CancelImport'](arg1);
}

export function ChooseOpeningCourseFile() {
  return window['go']['main']['NormalController']['ChooseOpeningCourseFile']();
}

export function ChoosePuzzleImportFile() {
  return window['go']['main']['NormalController']['ChoosePuzzleImportFile']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['NormalController']['CreateBackup'](arg1);
}

export function GetImportResult(arg1) {
  return window['go']['main']['NormalController']['GetImportResult'](arg1);
}

export function GetOpeningHome() {
  return window['go']['main']['NormalController']['GetOpeningHome']();
}

export function GetOpeningPosition(arg1, arg2, arg3) {
  return window['go']['main']['NormalController']['GetOpeningPosition'](arg1, arg2, arg3);
}

export function GetParentSummary() {
  return window['go']['main']['NormalController']['GetParentSummary']();
}

export function GetPracticeFilters() {
  return window['go']['main']['NormalController']['GetPracticeFilters']();
}

export function GetProfile() {
  return window['go']['main']['NormalController']['GetProfile']();
}

export function InspectOpeningCourseImport(arg1) {
  return window['go']['main']['NormalController']['InspectOpeningCourseImport'](arg1);
}

export function InspectPuzzleImport(arg1) {
  return window['go']['main']['NormalController']['InspectPuzzleImport'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['NormalController']['OpenDataFolder']();
}

export function PauseOpeningSession(arg1) {
  return window['go']['main']['NormalController']['PauseOpeningSession'](arg1);
}

export function PauseSession(arg1) {
  return window['go']['main']['NormalController']['PauseSession'](arg1);
}

export function PlayMove(arg1, arg2) {
  return window['go']['main']['NormalController']['PlayMove'](arg1, arg2);
}

export function PlayOpeningMove(arg1, arg2) {
  return window['go']['main']['NormalController']['PlayOpeningMove'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['NormalController']['Quit']();
}

export function RestartOpeningSession(arg1) {
  return window['go']['main']['NormalController']['RestartOpeningSession'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['NormalController']['RestoreBackup'](arg1);
}

export function ResumeOpeningSession() {
  return window['go']['main']['NormalController']['ResumeOpeningSession']();
}

export function ResumeSession() {
  return window['go']['main']['NormalController']['ResumeSession']();
}

export function RevealOpeningMove(arg1) {
  return window['go']['main']['NormalController']['RevealOpeningMove'](arg1);
}

export function RevealSolution(arg1) {
  return window['go']['main']['NormalController']['RevealSolution'](arg1);
}

export function SetOpeningDepth(arg1, arg2) {
  return window['go']['main']['NormalController']['SetOpeningDepth'](arg1, arg2);
}

export function StartFreePractice(arg1) {
  return window['go']['main']['NormalController']['StartFreePractice'](arg1);
}

export function StartGuided() {
  return window['go']['main']['NormalController']['StartGuided']();
}

export function StartOpeningCourseImport(arg1) {
  return window['go']['main']['NormalController']['StartOpeningCourseImport'](arg1);
}

export function StartOpeningLesson(arg1, arg2) {
  return window['go']['main']['NormalController']['StartOpeningLesson'](arg1, arg2);
}

export function StartOpeningReview(arg1) {
  return window['go']['main']['NormalController']['StartOpeningReview'](arg1);
}

export function StartPuzzleImport(arg1) {
  return window['go']['main']['NormalController']['StartPuzzleImport'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['NormalController']['UpdateProfile'](arg1);
}

export function UseHint(arg1) {
  return window['go']['main']['NormalController']['UseHint'](arg1);
}

export function UseOpeningHint(arg1) {
  return window['go']['main']['NormalController']['UseOpeningHint'](arg1);
}
