// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImport(arg1) {
  return window['go']['main']['NormalController']['CancelImport'](arg1);
}

export function ChoosePuzzleImportFile() {
  return window['go']['main']['NormalController']['ChoosePuzzleImportFile']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['NormalController']['CreateBackup'](arg1);
}

export function GetImportResult(arg1) {
  return window['go']['main']['NormalController']['GetImportResult'](arg1);
}

export function GetParentSummary() {
  return window['go']['main']['NormalController']['GetParentSummary']();
}

export function GetPracticeFilters() {
  return window['go']['main']['NormalController']['GetPracticeFilters']();
}

export function GetProfile() {
  return window['go']['main']['NormalController']['GetProfile']();
}

export function InspectPuzzleImport(arg1) {
  return window['go']['main']['NormalController']['InspectPuzzleImport'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['NormalController']['OpenDataFolder']();
}

export function PauseSession(arg1) {
  return window['go']['main']['NormalController']['PauseSession'](arg1);
}

export function PlayMove(arg1, arg2) {
  return window['go']['main']['NormalController']['PlayMove'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['NormalController']['Quit']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['NormalController']['RestoreBackup'](arg1);
}

export function ResumeSession() {
  return window['go']['main']['NormalController']['ResumeSession']();
}

export function RevealSolution(arg1) {
  return window['go']['main']['NormalController']['RevealSolution'](arg1);
}

export function StartFreePractice(arg1) {
  return window['go']['main']['NormalController']['StartFreePractice'](arg1);
}

export function StartGuided() {
  return window['go']['main']['NormalController']['StartGuided']();
}

export function StartPuzzleImport(arg1) {
  return window['go']['main']['NormalController']['StartPuzzleImport'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['NormalController']['UpdateProfile'](arg1);
}

export function UseHint(arg1) {
  return window['go']['main']['NormalController']['UseHint'](arg1);
}
