// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['RecoveryController']['CreateBackup'](arg1);
}

export function GetRecoveryState() {
  return window['go']['main']['RecoveryController']['GetRecoveryState']();
}

export function OpenDataFolder() {
  return window['go']['main']['RecoveryController']['OpenDataFolder']();
}

export function Quit() {
  return window['go']['main']['RecoveryController']['Quit']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['RecoveryController']['RestoreBackup'](arg1);
}
