// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBackup(arg1:boolean):Promise<string>;

export function GetRecoveryState():Promise<main.RecoveryState>;

export function OpenDataFolder():Promise<void>;

export function Quit():Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;
